// Embeds resources/shell/** into a TS module so the bundled daemon needs no files on disk.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const src = path.join(root, 'resources', 'shell');
const out = path.join(root, 'src', 'generated', 'shell-scripts.ts');

function walk(dir, base = '') {
  const res = {};
  for (const name of fs.readdirSync(dir).sort()) {
    const full = path.join(dir, name);
    const rel = base ? `${base}/${name}` : name;
    if (fs.statSync(full).isDirectory()) Object.assign(res, walk(full, rel));
    else res[rel] = fs.readFileSync(full, 'utf8');
  }
  return res;
}

const files = walk(src);
const body = `// GENERATED by scripts/gen-shell.mjs from resources/shell — do not edit.\nexport const SHELL_SCRIPTS: Record<string, string> = ${JSON.stringify(files, null, 2)};\n`;
const check = process.argv.includes('--check');
let cur = '';
try {
  cur = fs.readFileSync(out, 'utf8');
} catch {}
if (check) {
  if (cur !== body) {
    console.error('src/generated/shell-scripts.ts is out of date; run: node scripts/gen-shell.mjs');
    process.exit(1);
  }
} else if (cur !== body) {
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, body);
  console.log('wrote', path.relative(root, out));
}
