import fs from 'node:fs';
import path from 'node:path';
import type { MemoryStore } from './store';
import type { MemoryItem, MemoryKind, SkillItem } from './types';
import { displayPath } from './heuristics';
import { isInside, projectOfScope, rankItems, rankSkills } from './ranking';

export interface ContextOptions {
  cwd?: string;
  query?: string;
  budgetChars?: number;
  /** Include the user's own NOTES.md. */
  notes?: boolean;
  skills?: boolean;
  home?: string;
  /** Restrict to these ids (used to inject only what the agent has not been shown yet). */
  only?: { items: Set<string>; skills: Set<string> };
}

export interface BuiltContext {
  text: string;
  itemIds: string[];
  skillIds: string[];
}

const KIND_ORDER: MemoryKind[] = ['preference', 'convention', 'workflow', 'lesson', 'fact', 'project', 'environment'];
const KIND_LABEL: Record<MemoryKind, string> = {
  preference: 'Preferences',
  convention: 'Conventions',
  workflow: 'Workflows',
  lesson: 'Lessons',
  fact: 'Facts',
  project: 'Projects',
  environment: 'Environment',
};

function readNotes(store: MemoryStore, max = 1800): string {
  try {
    return fs.readFileSync(store.paths.memoryNotes, 'utf8').trim().slice(0, max);
  } catch {
    return '';
  }
}

function group(items: MemoryItem[]): string {
  const lines: string[] = [];
  for (const kind of KIND_ORDER) {
    const part = items.filter((i) => i.kind === kind);
    if (!part.length) continue;
    lines.push(`**${KIND_LABEL[kind]}**`);
    for (const i of part) lines.push(`- ${i.text}`);
  }
  return lines.join('\n');
}

/**
 * Assemble the memory an agent should start with: the strongest global items, everything
 * relevant to the current project, matching skills, and the user's own notes, within a budget.
 */
export function buildContext(store: MemoryStore, opts: ContextOptions = {}): BuiltContext {
  const budget = opts.budgetChars ?? 6000;
  const home = opts.home;
  const ranked = rankItems(store.listItems(), { cwd: opts.cwd, query: opts.query }).filter((r) => !opts.only || opts.only.items.has(r.item.id));

  const globalPicked: MemoryItem[] = [];
  const projectPicked = new Map<string, MemoryItem[]>();
  let used = 0;
  const notes = opts.notes === false || opts.only ? '' : readNotes(store);
  used += notes.length + 80;

  const skills = opts.skills === false ? [] : rankSkills(store.listSkills(), { cwd: opts.cwd, query: opts.query }).filter((s) => s.score > 0.25 && (!opts.only || opts.only.skills.has(s.skill.id))).slice(0, 6);
  const skillBudget = skills.length ? Math.min(900, Math.floor(budget * 0.2)) : 0;
  const itemBudget = budget - skillBudget;

  for (const { item, score } of ranked) {
    if (score < 0.12 && !item.pinned) continue;
    const proj = projectOfScope(item.scope);
    // Other projects' knowledge only appears when the query points at it.
    if (proj && !(opts.cwd && isInside(opts.cwd, proj)) && score < 0.5) continue;
    const cost = item.text.length + 4;
    if (used + cost > itemBudget) continue;
    used += cost;
    if (proj) projectPicked.set(proj, [...(projectPicked.get(proj) ?? []), item]);
    else globalPicked.push(item);
  }

  const parts: string[] = [];
  if (globalPicked.length) parts.push(`### About you and your setup\n${group(globalPicked)}`);
  for (const [proj, items] of projectPicked) parts.push(`### Project: ${path.basename(proj)} (${displayPath(proj, home)})\n${group(items)}`);
  const skillIds: string[] = [];
  if (skills.length) {
    const lines = ['### Learned skills (procedures that worked before)'];
    let sb = 0;
    for (const { skill } of skills) {
      const l = `- **${skill.name}** — ${skill.whenToUse || skill.description} (steps: ${skill.steps.map((s) => '`' + s + '`').join(' → ')})`;
      if (sb + l.length > skillBudget) break;
      sb += l.length;
      lines.push(l);
      skillIds.push(skill.id);
    }
    if (lines.length > 1) parts.push(lines.join('\n'));
  }
  if (notes) parts.push(`### Your notes\n${notes}`);

  const itemIds = [...globalPicked, ...[...projectPicked.values()].flat()].map((i) => i.id);
  const text = parts.length ? parts.join('\n\n') : '';
  return { text, itemIds, skillIds };
}

// ---------------------------------------------------------------- generated views

export function renderIndex(store: MemoryStore, home?: string): string {
  const items = store.listItems();
  const skills = store.listSkills();
  const lines: string[] = [
    '# Jaffer memory',
    '',
    '> Generated by Jaffer from your session. It updates itself as you work.',
    '> Edit with `jaffer memory` or the Memory panel. Put your own notes in `NOTES.md` (never overwritten).',
    '',
  ];
  const global = items.filter((i) => i.scope === 'global');
  if (global.length) {
    lines.push('## Global', '', group(rankItems(global).map((r) => r.item)), '');
  }
  const scopes = [...new Set(items.filter((i) => i.scope !== 'global').map((i) => i.scope))];
  for (const scope of scopes) {
    const proj = projectOfScope(scope)!;
    lines.push(`## Project: ${path.basename(proj)}`, '', `_${displayPath(proj, home)}_`, '', group(rankItems(items.filter((i) => i.scope === scope)).map((r) => r.item)), '');
  }
  if (skills.length) {
    lines.push('## Skills', '');
    for (const s of skills) lines.push(`- **${s.name}** — ${s.whenToUse || s.description}`);
    lines.push('');
  }
  if (!global.length && !scopes.length && !skills.length) lines.push('_Nothing learned yet — keep working; Jaffer is watching._', '');
  return lines.join('\n');
}

export function skillMarkdown(s: SkillItem): string {
  return [`# ${s.name}`, '', s.description, '', `**When to use:** ${s.whenToUse}`, '', '## Steps', ...s.steps.map((st, i) => `${i + 1}. \`${st}\``), ''].join('\n');
}

/** Refresh MEMORY.md and the per-skill files from the store. */
export function writeViews(store: MemoryStore, home?: string): void {
  store.writeView(store.paths.memoryIndex, renderIndex(store, home));
  const skills = store.listSkills();
  const keep = new Set<string>();
  for (const s of skills) {
    const file = path.join(store.paths.memorySkillsDir, `${skillSlug(s)}.md`);
    keep.add(path.basename(file));
    store.writeView(file, skillMarkdown(s));
  }
  try {
    for (const f of fs.readdirSync(store.paths.memorySkillsDir)) {
      if (f.endsWith('.md') && !keep.has(f)) fs.rmSync(path.join(store.paths.memorySkillsDir, f), { force: true });
    }
  } catch {
    /* dir may not exist yet */
  }
  const policy = store.paths.memoryPolicy;
  void policy;
}

export function skillSlug(s: SkillItem): string {
  const base = s.name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40);
  return `${base || 'skill'}-${s.id.slice(2, 6)}`;
}
